name: master
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - seaborn
  - pytorch
#  - pytorch-cuda=12.4
#  - torchvision